# This is a basic workflow to help you get started with Actions

name: Create a Pdf when something is pushed

on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Automaticly create a PDF after Push
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Convert to pdf
      id: convert-to-pdf
      uses: Konradrundfunk/pdflatex-action@v1.0.0
      with:
        texFile: ./Kurzwellenausbreitung.tex
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: file.pdf
        path: file.pdf
