# This is a basic workflow to help you get started with Actions

name: Create a Pdf when something is pushed

on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Automaticly create a PDF after Push
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: convert to pdf
      id: convert-to-pdf
      uses: Konradrundfunk/pdflatex-action@1.1.2
      with:
        texFile: ./main.tex

    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: Amateurfunklehrgang
        path: main.pdf
    - run: ls
#
#    - name: Commit changes
#      uses: EndBug/add-and-commit@v7
#      with:
#        default_author: github_actions
#        author_email: 33392939+Konradrundfunk@users.noreply.github.comTage beim Urwald für knapp 25 Euro einen Schultaschenrechner gekauft. Casio fx-911 de-x. Meiner Meinung nach kann der alles, was man irgendwie mal brauchen könnte.
#        message: 'Auto commit pdfs.'
#        add: '*.pdf'